# -*- coding: utf-8 -*-
"""ProjectTesting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h_0gIp935lSoo136GiOGgoRPB8JtXDh
"""

!pip install openai
!pip install pymysql
!pip install pymongo[srv]
!pip install sshtunnel

# imoprt libraries, install and connect to openAI
import pandas as pd
import openai
import json
import getpass
import pymysql
from pymongo import MongoClient
from sshtunnel import SSHTunnelForwarder

api_key = getpass.getpass("Enter your OpenAI API key: ")
client = openai.OpenAI(api_key=api_key)

# call data into dataframes

cards_df = pd.read_csv("cards_data.csv", nrows=1000)
transactions_df = pd.read_csv("transactions_data.csv", nrows=1000)
users_df = pd.read_csv("users_data.csv", nrows=1000)

# create variables for data columns

cards_df_columns = list(cards_df.columns)
transactions_df_columns = list(transactions_df.columns)
users_df_columns = list(users_df.columns)

# Load the NoSQL datasets (MongoDB datasets)
with open("customers.json") as f:
    customers_data = json.load(f)

with open("products.json") as f:
    products_data = json.load(f)

with open("ratings.json") as f:
    ratings_data = json.load(f)

# Prepare column names and sample data for both datasets (using the first 5 entries for sample)
customers_columns = list(customers_data[0].keys())  # Extract keys (column names) from the first entry
customers_sample = customers_data[:5]  # Get first 5 records as sample

products_columns = list(products_data[0].keys())  # Extract keys (column names) from the first entry
products_sample = products_data[:5]  # Get first 5 records as sample

ratings_columns = list(ratings_data[0].keys())  # Extract keys (column names) from the first entry
ratings_sample = ratings_data[:5]  # Get first 5 records as sample

# get user's input (make it inputable after testing)

user_input = "Return the names of products with a rating of 1, along with the customer's ID who gave the rating."

# use openAI to determine which data sets we are working with based on user_input

dataset_fields_map = {
    "users_df": users_df_columns,
    "cards_df": cards_df_columns,
    "transactions_df": transactions_df_columns,
    "customers_json": customers_columns,
    "products_json": products_columns,
    "ratings_json": ratings_columns
}

def which_dataset(user_input, dataset_fields):
  schema_description = "\n".join([
    f"{name}: {' ,'.join(fields)}" for name, fields in dataset_fields.items()
    ])

  prompt = f"""
  You are an expert data scientist.

  Here are the available datasets and the fields they contain:
  {schema_description}

  The user asked:
  \"{user_input}\"

  Based on the fields and the question, which dataset(s) are needed to answer this question?
  In most cases, only one dataset is needed. However, in some cases, a join function is needed and so two or more data sets will be required.
  Respond ONLY with the dataset name(s) – "cards_df", "transactions_df", or "users_df" – seperated by a comma. No explanation.
  """

  response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "user", "content": prompt}
      ])

  datasets = response.choices[0].message.content
  return datasets

datasets = which_dataset(user_input, dataset_fields_map)
datasets_list = datasets.split(", ")
print(datasets_list)

# use openAI to create a query using these data sets

def create_query(user_input):
  datasets = which_dataset(user_input, dataset_fields_map)
  datasets_list = datasets.split(", ")

  # Ensure only datasets of the same type (CSV with CSV, JSON with JSON) are selected
  csv_datasets = ["cards_df", "transactions_df", "users_df"]
  json_datasets = ["customers_json", "products_json", "ratings_json"]

    # Separate CSV and JSON datasets
  selected_csv_datasets = [dataset for dataset in datasets_list if dataset in csv_datasets]
  selected_json_datasets = [dataset for dataset in datasets_list if dataset in json_datasets]

    # If both types of datasets (CSV and JSON) are mixed, raise an error
  if selected_csv_datasets and selected_json_datasets:
      raise ValueError("Cannot mix CSV (MySQL) and JSON (MongoDB) datasets. Please ensure only one type is selected.")


  # make a dictionary containing the datasets we are using and their columns
  columns_dict = {}
  for dataset in dataset_fields_map:
    if dataset in datasets_list:
      columns_dict[dataset] = dataset_fields_map[dataset]

  # make a schema description ONLY for the datasets we are using
  schema_description = "\n".join([
    f"{name}: {' ,'.join(fields)}" for name, fields in columns_dict.items()
    ])

  # Check if the datasets are NoSQL (JSON) or SQL (CSV)
  is_nosql = any(dataset in ["customers_json", "products_json", "ratings_json"] for dataset in datasets_list)

  # Based on the dataset type, create the right query prompt
  if is_nosql:
      prompt = f"""
      You are an expert MongoDB query writer.
      Here are the datasets we are using and the fields they contain:
      {schema_description}

      The user asked:
      \"{user_input}\"

      Return ONLY the MongoDB query (in JSON format) that responds to what the user asked.
      """
  else:
      prompt = f"""
      You are an expert data scientist.
      Here are the datasets we are using and the fields they contain:
      {schema_description}

      The user asked:
      \"{user_input}\"

      Return ONLY the SQL query that responds to what the user asked.
      """

  # return the query that the openAI API gave us
  response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "user", "content": prompt}
        ])

  query = response.choices[0].message.content
  return query

query = create_query(user_input)
print(query)

# FUNCTION: GENERATE QUERY
def create_query(user_input):
    datasets = which_dataset(user_input, dataset_fields_map)
    datasets_list = datasets.split(", ")

    csv_datasets = ["cards_df", "transactions_df", "users_df"]
    json_datasets = ["customers_json", "products_json", "ratings_json"]

    selected_csv = [d for d in datasets_list if d in csv_datasets]
    selected_json = [d for d in datasets_list if d in json_datasets]

    if selected_csv and selected_json:
        raise ValueError("Cannot mix CSV (MySQL) and JSON (MongoDB) datasets.")

    selected_type = "nosql" if selected_json else "sql"

    columns_dict = {dataset: dataset_fields_map[dataset] for dataset in datasets_list}
    schema_description = "\n".join([f"{name}: {', '.join(fields)}" for name, fields in columns_dict.items()])

    prompt = f"""
    You are an expert {"MongoDB" if selected_type == "nosql" else "SQL"} query writer.
    Here are the datasets and fields:
    {schema_description}

    The user asked:
    \"{user_input}\"

    Return ONLY the {"MongoDB query (JSON format)" if selected_type == "nosql" else "SQL query"}.
    """

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip(), selected_type

# FUNCTION: EXECUTE QUERY
def run_query(query, db_type):
    ssh_host = 'ec2-3-140-198-20.us-east-2.compute.amazonaws.com'
    ssh_user = 'ubuntu'
    ssh_key = 'dsci351.pem'

    if db_type == "sql":
        with SSHTunnelForwarder(
            (ssh_host, 22),
            ssh_username=ssh_user,
            ssh_pkey=ssh_key,
            remote_bind_address=('127.0.0.1', 3306)
        ) as tunnel:
            connection = pymysql.connect(
                host='127.0.0.1',
                user='root',
                password='Dsci351',
                database='transactions_db',
                port=tunnel.local_bind_port
            )
            with connection.cursor() as cursor:
                cursor.execute(query)
                result = cursor.fetchall()
                column_names = [desc[0] for desc in cursor.description]
                df = pd.DataFrame(result, columns=column_names)
                print(df)

    elif db_type == "nosql":
        with SSHTunnelForwarder(
            (ssh_host, 22),
            ssh_username=ssh_user,
            ssh_pkey=ssh_key,
            remote_bind_address=('127.0.0.1', 27017)
        ) as tunnel:
            client = MongoClient('127.0.0.1', tunnel.local_bind_port)
            db = client["ecommerce"]

            # You may want to programmatically decide which collection to use, here's a sample logic:
            if "customers" in query.lower():
                collection = db["customers"]
            elif "products" in query.lower():
                collection = db["products"]
            elif "ratings" in query.lower():
                collection = db["ratings"]
            else:
                raise ValueError("Unknown collection.")

            try:
                mongo_query = eval(query)  # only works if query is a valid dict string
                result = list(collection.find(mongo_query).limit(5))
                print(pd.DataFrame(result))
            except Exception as e:
                print("Error running MongoDB query:", e)

# MAIN FLOW
user_input = "List top 5 clients from the transactions table"
query, db_type = create_query(user_input)
print("Generated Query:\n", query)
run_query(query, db_type)

# now we need to run the query using pymysql
import pymysql
from sshtunnel import SSHTunnelForwarder

# SSH credentials for your EC2 instance
ssh_host = 'ec2-52-14-234-112.us-east-2.compute.amazonaws.com'  # Your EC2 public IP
ssh_user = 'ubuntu'  # The SSH user (typically 'ubuntu' for EC2)
ssh_key = 'dsci351.pem'  # Path to your private SSH key for EC2

# MySQL credentials
mysql_host = 'localhost'  # MySQL is running locally on the EC2 instance
mysql_user = 'root'  # MySQL user (or use the correct one)
mysql_password = 'Dsci351'  # Replace with your actual MySQL password
mysql_db = 'transactions_db'  # Database you want to connect to

# Set up SSH tunnel
with SSHTunnelForwarder(
    (ssh_host, 22),  # EC2 host and SSH port
    ssh_username=ssh_user,
    ssh_pkey=ssh_key,
    remote_bind_address=('127.0.0.1', 3306)  # Forward MySQL port (3306)
) as tunnel:
    # Connect to MySQL server over the tunnel
    connection = pymysql.connect(
        host=mysql_host,
        user=mysql_user,
        password=mysql_password,
        database=mysql_db,
        port=tunnel.local_bind_port  # Local port used for the tunnel
    )

    with connection.cursor() as cursor:
        cursor.execute(query)  # Replace with your query
        result = cursor.fetchall()
        column_names = [desc[0] for desc in cursor.description]
        #df_result = pd.DataFrame(result)

    # View the top few rows
    #print(df_result.head())
    #print(result)
    df = pd.DataFrame(result, columns=column_names)
    print(df)

from pymongo import MongoClient
from sshtunnel import SSHTunnelForwarder

ssh_host = 'ec2-52-14-234-112.us-east-2.compute.amazonaws.com'
ssh_user = 'ubuntu'
ssh_key = 'dsci351.pem'  # Make sure this is uploaded to Colab

mongo_host = '127.0.0.1'
mongo_port = 27017  # default MongoDB port

with SSHTunnelForwarder(
    (ssh_host, 22),
    ssh_username=ssh_user,
    ssh_pkey=ssh_key,
    remote_bind_address=(mongo_host, mongo_port)
) as tunnel:
    client = MongoClient('127.0.0.1', tunnel.local_bind_port)
    db = client["ecommerce"]
    # Access collections one by one
    customers = db["customers"]
    products = db["products"]
    ratings = db["ratings"]

# --------- STREAMLIT UI ----------

# Install necessary libraries (if not already installed)
!pip install pymysql sshtunnel pymongo[srv] openai --quiet

import pandas as pd
import openai
import json
import getpass
import pymysql
import re
import ast
from pymongo import MongoClient
from sshtunnel import SSHTunnelForwarder

# OpenAI API Key
api_key = getpass.getpass("Enter your OpenAI API key: ")
client = openai.OpenAI(api_key=api_key)

cards_df = pd.read_csv("cards_data.csv", nrows=1000)
transactions_df = pd.read_csv("transactions_data.csv", nrows=1000)
users_df = pd.read_csv("users_data.csv", nrows=1000)

cards_df_columns = list(cards_df.columns)
transactions_df_columns = list(transactions_df.columns)
users_df_columns = list(users_df.columns)

with open("customers.json") as f:
    customers_data = json.load(f)
with open("products.json") as f:
    products_data = json.load(f)
with open("ratings.json") as f:
    ratings_data = json.load(f)

customers_columns = list(customers_data[0].keys())
products_columns = list(products_data[0].keys())
ratings_columns = list(ratings_data[0].keys())

#user_input = "Show me the data for user with ID 4000"
#user_input = "Delete the user with ID 4000"
#user_input = "Show me the data for card ID 2731"
#user_input = "Update the cvv of card ID 2731 to 123."
#user_input = "Show me the data for user with client_id 4000"
#user_input = "Add a new user in the users_df with client_id 4000 and is a female and lives at address: 123 Trojan Lane."
#user_input = "Get the top 5 clients by total transaction amount."
#user_input = "Which cards belong to users who made a purchase over $1000?"
#user_input = "List all users who are born in 1999"
#user_input = "What are some sample rows from the transactions_df table?"
#user_input = "Show me the columns in the users_df table."
#user_input = "Return card_id values for all client_id values greater than 1900, don't show more than 5 rows"

#user_input = "Update the price of product with id 702 to 12000"
#user_input = "Show me the name and price for product with id 702 and id 705"
#user_input = "Insert a new product called 'Macbook Air' with product id 702 and price as 10000 and a new product called 'Iphone 18' with product id 705 and price as 600"
user_input = "find the top 5 products with the highest average rating"
#user_input = "List all ratings given by customer with ID 103416."
#user_input = "Show me a sample document from the products_json collection."
#user_input = "Find the names of products that have a unit price less than 3"

dataset_fields_map = {
    "users_df": users_df_columns,
    "cards_df": cards_df_columns,
    "transactions_df": transactions_df_columns,
    "customers_json": customers_columns,
    "products_json": products_columns,
    "ratings_json": ratings_columns
}

def which_dataset(user_input, dataset_fields):
    schema_description = "\n".join([
        f"{name}: {', '.join(fields)}" for name, fields in dataset_fields.items()
    ])

    prompt = f"""
You are an expert data scientist.

Here are the available datasets and the fields they contain:
{schema_description}

Your task is to decide which dataset(s) are necessary to answer the user's question.

Rules:
- Use only dataset names exactly as provided above.
- Select all datasets that contain any field referenced directly or indirectly in the question.
- If multiple datasets are needed to join data (e.g., to get a name from one and ratings from another), include both.
- If you're unsure, err on the side of including more datasets rather than fewer.

The user asked:
\"{user_input}\"

Return ONLY the dataset names (like "ratings_json", "products_json") as a comma-separated list. No explanation.
"""

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

import re
import ast

def create_query(user_input):
    datasets = which_dataset(user_input, dataset_fields_map)
    datasets_list = [d.strip() for d in datasets.split(",")]

    csv_datasets = ["cards_df", "transactions_df", "users_df"]
    json_datasets = ["customers_json", "products_json", "ratings_json"]

    selected_csv_datasets = [d for d in datasets_list if d in csv_datasets]
    selected_json_datasets = [d for d in datasets_list if d in json_datasets]

    if selected_csv_datasets and selected_json_datasets:
        raise ValueError("Cannot mix SQL (CSV) and NoSQL (JSON) datasets.")

    columns_dict = {d: dataset_fields_map[d] for d in datasets_list}
    schema_description = "\n".join([f"{k}: {', '.join(v)}" for k, v in columns_dict.items()])

    is_nosql = bool(selected_json_datasets)

    # Dynamic prompt based on dataset type
    if is_nosql:
        prompt = f"""
You are an expert MongoDB query writer.

Here are the datasets and their fields:
{schema_description}

The user asked:
\"{user_input}\"

Return ONLY a valid MongoDB query in **Python dictionary/list syntax**, suitable for execution with the PyMongo library in Python.

Format:
- For `.find()`:
    {{ "filter": {{...}}, "projection": {{...}} }}
- For `.aggregate()`:
    [{{"$match": {{...}}}}, ...]
- For `.insertOne()`:
    {{ "insertOne": {{...}} }}
- For `.insertMany()`:
    {{ "insertMany": [{{...}}, {{...}}] }}
- For `.updateOne()`:
    {{ "updateOne": {{ "filter": {{...}}, "update": {{...}} }} }}
- For `.updateMany()`:
    {{ "updateMany": {{ "filter": {{...}}, "update": {{...}} }} }}
- For `.deleteOne()`:
    {{ "deleteOne": {{...}} }}

DO NOT return raw Mongo shell syntax or explanation — only the query object itself.
"""
    else:
        prompt = f"""
You are an expert SQL query writer.

Here are the tables and their fields:
{schema_description}

The user asked:
\"{user_input}\"

Return ONLY a valid **MySQL** query using SQL syntax — no explanation, no markdown, no comments.
"""

    # Run the prompt through GPT
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}]
    )

    raw_response = response.choices[0].message.content.strip()
    print("Raw query string:", raw_response)

    if not raw_response:
        raise ValueError("Received empty response for query.")

    if is_nosql:
        query_str = re.sub(r"^```.*?\n|\n```$", "", raw_response)

        try:
            query_obj = ast.literal_eval(query_str)

            if isinstance(query_obj, list):
                query = query_obj  # Aggregation pipeline
            elif isinstance(query_obj, dict):
                if "aggregate" in query_obj:  # Embedded aggregation
                    query = query_obj["aggregate"]
                elif "filter" in query_obj or "projection" in query_obj:  # Find query
                    filter_dict = query_obj.get("filter", {})
                    projection_dict = query_obj.get("projection", None)
                    query = {"filter": filter_dict, "projection": projection_dict}
                else:
                    # Handle insertOne, updateOne, deleteOne, etc.
                    query = query_obj
            else:
                raise ValueError("Query is not valid Mongo format")
        except Exception as e:
            raise ValueError(f"Error parsing Mongo query: {e}")
    else:
        query = raw_response  # Return raw SQL query string

    return query, is_nosql, datasets_list

query, is_nosql, datasets_list = create_query(user_input)
print(query)
print("Is NoSQL?", is_nosql)
print("Datasets:", datasets_list)

if not is_nosql:
    ssh_host = 'ec2-3-144-6-200.us-east-2.compute.amazonaws.com'
    ssh_user = 'ubuntu'
    ssh_key = 'dsci351.pem'  # Upload this file via Colab sidebar if needed

    mysql_host = 'localhost'
    mysql_user = 'root'
    mysql_password = 'Dsci351'
    mysql_db = 'transactions_db'

    with SSHTunnelForwarder(
        (ssh_host, 22),
        ssh_username=ssh_user,
        ssh_pkey=ssh_key,
        remote_bind_address=('127.0.0.1', 3306)
    ) as tunnel:
        connection = pymysql.connect(
            host=mysql_host,
            user=mysql_user,
            password=mysql_password,
            database=mysql_db,
            port=tunnel.local_bind_port
        )
        with connection.cursor() as cursor:
            cursor.execute(query)  # Execute the INSERT query
            connection.commit()  # Commit the changes
            if query.strip().lower().startswith("select"):
                result = cursor.fetchall()  # This is for SELECT queries
                column_names = [desc[0] for desc in cursor.description]
                df = pd.DataFrame(result, columns=column_names)
                print(df)
            else:
                print("Query executed successfully, no data returned.")

if is_nosql:
    ssh_host = 'ec2-3-144-6-200.us-east-2.compute.amazonaws.com'
    ssh_user = 'ubuntu'
    ssh_key = 'dsci351.pem'
    mongo_port = 27017

    from pymongo import MongoClient
    from sshtunnel import SSHTunnelForwarder
    import time
    import pandas as pd

    with SSHTunnelForwarder(
        (ssh_host, 22),
        ssh_username=ssh_user,
        ssh_pkey=ssh_key,
        remote_bind_address=('127.0.0.1', mongo_port),
        local_bind_address=('127.0.0.1', 27017)
    ) as tunnel:

        if tunnel.is_active:
            print("SSH Tunnel established successfully.")
            time.sleep(2)

            client = MongoClient('127.0.0.1', tunnel.local_bind_port)
            db = client["ecommerce"]

            collections = {
                "customers_json": db["customers_json"],
                "products_json": db["products_json"],
                "ratings_json": db["ratings_json"]
            }

            active_collection = collections[datasets_list[0]]

            if isinstance(query, dict):
                if "insertOne" in query:
                    result = active_collection.insert_one(query["insertOne"])
                    print(f"Inserted ID: {result.inserted_id}")

                elif "insertMany" in query:
                    result = active_collection.insert_many(query["insertMany"])
                    print(f"Inserted IDs: {result.inserted_ids}")

                elif "updateOne" in query:
                    result = active_collection.update_one(
                        query["updateOne"]["filter"], query["updateOne"]["update"]
                    )
                    print(f"Matched: {result.matched_count}, Modified: {result.modified_count}")

                elif "updateMany" in query:
                    result = active_collection.update_many(
                        query["updateMany"]["filter"], query["updateMany"]["update"]
                    )
                    print(f"Matched: {result.matched_count}, Modified: {result.modified_count}")

                elif "deleteOne" in query:
                    result = active_collection.delete_one(query["deleteOne"])
                    print(f"Deleted Count: {result.deleted_count}")

                elif "filter" in query:
                    result = list(active_collection.find(query["filter"], query.get("projection")).limit(5))
                    df = pd.DataFrame(result)
                    print("DataFrame head:", df.head())

                else:
                    print("Unrecognized operation:", query)

            elif isinstance(query, list):  # aggregation
                result = list(active_collection.aggregate(query))
                df = pd.DataFrame(result)
                print("Aggregation result:")
                print(df.head())

        else:
            print("Failed to establish SSH tunnel.")